# Generated by Django 6.0.5 on 2026-08-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("uncleared", "Uncleared"),
                    ("cleared", "Cleared"),
                    ("reconciled", "Reconciled"),
                ],
                default="uncleared",
                max_length=20,
            ),
        ),
    ]
